robot_name: franka

# Detector used to teleoperate the robot
detector:
  _target_: openteach.components.detector.oculus_stick.OculusVRStickDetector
  host: ${host_address}
  controller_state_pub_port: ${transformed_position_keypoint_port}
  
# Operators used to retarget the keypoints
operators:
  - 
    _target_: openteach.components.operators.franka_stick.FrankaOperator
    host: ${host_address}
    controller_state_port: ${transformed_position_keypoint_port}
    save_target_states: ${save_target_states}
    exp_name: ${exp_name}
    demo_num: ${demo_num}


